# Generated by Django 4.2.15 on 2024-09-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_bookinstance'),
        ('bboard', '0006_alter_bb_rubric'),
    ]

    operations = [
    ]
