# Generated by Django 4.2.15 on 2024-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_merge_0002_bookinstance_0006_alter_bb_rubric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.AddField(
            model_name='rubric',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
