# Generated by Django 4.2.15 on 2024-09-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_delete_bookinstance_rubric_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-order', '-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
