# Generated by Django 4.2.15 on 2024-09-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_revrubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'get_latest_by': 'published', 'ordering': ['-published', 'title'], 'permissions': (('can_create', 'Can create anything'),), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
