# Generated by Django 4.2.15 on 2024-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_alter_bb_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
    ]
