# Generated by Django 4.2.15 on 2024-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
