# Generated by Django 4.2.15 on 2024-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_bb_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevRubric',
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='order',
        ),
        migrations.AddField(
            model_name='rubric',
            name='photo',
            field=models.CharField(db_index=True, default=None, max_length=20, unique=True, verbose_name='Названиеd'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
