# Generated by Django 4.2.15 on 2024-10-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0014_alter_rubric_options_bb__content_rendered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='_content_rendered',
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
