# Generated by Django 5.2.5 on 2025-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0016_alter_rubric_options_alter_bb_rubric_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
